name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python app.py
        cat README.md
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@eugeneyan.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
